//User Action Types
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_RESET = 'CREATE_USER_RESET';




//Organization Action Types
export const CREATE_ORGANIZATION_REQUEST = 'CREATE_ORGANIZATION_REQUEST';
export const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_FAIL = 'CREATE_ORGANIZATION_FAIL';
export const CREATE_ORGANIZATION_RESET = 'CREATE_ORGANIZATION_RESET';

export const ORG_LIST_REQUEST = 'ORG_LIST_REQUEST';
export const ORG_LIST_SUCCESS = 'ORG_LIST_SUCCESS';
export const ORG_LIST_FAIL = 'ORG_LIST_FAIL';
export const ORG_LIST_RESET = 'ORG_LIST_RESET';

export const ORG_BYID_REQUEST = 'ORG_BYID_REQUEST';
export const ORG_BYID_SUCCESS = 'ORG_BYID_SUCCESS';
export const ORG_BYID_FAIL = ' ORG_BYID_FAIL';
export const ORG_BYID_RESET = 'ORG_BYID_RESET';

export const ADD_ORGUSER_REQUEST = 'ADD_ORGUSER_REQUEST';
export const ADD_ORGUSER_SUCCESS = 'ADD_ORGUSER_SUCCESS';
export const ADD_ORGUSER_FAIL = 'ADD_ORGUSER_FAIL';
export const ADD_ORGUSER_RESET = 'ADD_ORGUSER_RESET';